### ISSUE TITLE
Frontend: Busca de imóveis

### ISSUE THREAD

**Issue by waldrey** [cobertura-io/php#3]
A estrutura base da tela foi desenvolvida totalmente utilizando bootstrap. Foco atualmente será na conclusão da tela conforme foi feito pelo @srvaz 

**TELA ATUALMENTE:**
![](https://i.imgur.com/B05Bjmo.jpg)

Será necessário basicamente estilizar e deixar um padrão nos *card's*.

### branch
`frontend_buscaimoveis`

**Comment by DenielPereira** [comment]
A principio os cards foram estilizados, porem ainda faltam alguns artefatos visuais que deixariam a tela mais agradável. 

**Imagem da tela atualmente:**

![whatsapp image 2018-11-25 at 12 35 39](https://user-images.githubusercontent.com/26224449/48980386-54f3b180-f0af-11e8-9689-a0a8d864964e.jpeg)
