### ISSUE TITLE
Frontend: Imóvel

### ISSUE THREAD

**Issue by waldrey** [cobertura-io/php#4]
A estrutura base da tela foi desenvolvida totalmente utilizando bootstrap. Foco atualmente será na conclusão da tela conforme foi feito pelo @srvaz 

**TELA ATUALMENTE:**
![](https://i.imgur.com/srvbRnm.jpg)

### o que falta

- [x] diminuir tamanho da foto da casa e adicionar um tipo de slide
- [x] estilizar e organizar as informações da casa e descrição
- [x] estilizar a foto do corretor e alinhar nome e enviar mensagem
- [x] melhorar o card que informa valor de alugel e outras variáveis do imóvel.

### branch
`frontend_imovel`

**Comment by DenielPereira** [comment]
A tela foi estilizada, porém ainda faltam alguns elementos a serem tratados:

- [ ] Slider "slick" ainda não funciona
- [ ] Responsividade

**Comment by waldrey** [comment]
pull request #18 merged
